spring:
  datasource:  
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin1234
    url: jdbc:mysql://localhost:3306/insurance_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
           
# eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8888/eureka, http://localhost:8889/eureka  