spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin1234
    url: jdbc:mysql://localhost:3306/pharmacydb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
store:
  storeNo: 101
  storeName: Ganesh Pharma
  location: krantinagar
  mobileNo: 909090